<a href="https://colab.research.google.com/github/kapuGayathri/Pandas/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

if 5<3:
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)
  print("end")

In [ ]:
if 5<3:
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)
print("end")

end

functions

In [ ]:
def xyz():
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)

In [ ]:
xyz()

yes
10

In [ ]:
def mnp(m):
  k=10
  c=m+k
  print(c)

In [ ]:
mnp(9)

19

In [ ]:
def mnp(m,n,p='mango'):
  print(p)

In [ ]:
mnp(9,12)

mango

In [ ]:
type(100)

int

In [ ]:
def newf():
  print(100)
  print(200)
newf()

100
200

In [ ]:
def newf():
  print(100)
  print(200)
  return 150
newf()

100
200

150

In [ ]:
def newf():
  print(100)
  print(200)
  return 150
newf()

100
200

150

In [ ]:
def onef(x):
 return x*7 +23

In [ ]:
twof=lambda x: x*7+23

In [ ]:
twof(5)

58

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.DataFrame({
    "A":[10,20,30,40,50],
    "b":['a','b','c','d','e']
})

    A  b
0  10  a
1  20  b
2  30  c
3  40  d
4  50  e

In [ ]:
pd.DataFrame({
    "A":[10,20,30,40,50],
    "b":['a','b','c','d','e'],
    "c":np.random.randint(65)
})

    A  b   c
0  10  a  52
1  20  b  52
2  30  c  52
3  40  d  52
4  50  e  52

In [ ]:
pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=["a","b","c","d"]
)

   a  b  c  d
0  5  8  2  4
1  4  3  4  0
2  2  0  8  1
3  2  1  3  0
4  1  0  6  7
5  4  3  7  6
6  7  8  4  1
7  5  5  5  5
8  0  7  6  0
9  8  2  6  8

In [ ]:
np.random.rand(10,3)

array([[0.17990643, 0.23586317, 0.70072275],
       [0.24875609, 0.49165861, 0.43957495],
       [0.81348816, 0.0758525 , 0.59295069],
       [0.0552067 , 0.52798709, 0.76563763],
       [0.89332913, 0.75429337, 0.65314467],
       [0.92889835, 0.76540823, 0.03803804],
       [0.63612406, 0.12650306, 0.73403244],
       [0.15124685, 0.31784389, 0.26012324],
       [0.27242753, 0.89310492, 0.9270984 ],
       [0.7274041 , 0.62609354, 0.85764748]])

In [ ]:
np.random.rand(10,3).round(2)

array([[0.42, 0.58, 0.73],
       [0.97, 0.95, 0.48],
       [0.27, 0.93, 0.57],
       [0.95, 0.67, 0.94],
       [0.25, 0.87, 0.36],
       [0.62, 0.89, 0.91],
       [0.02, 0.62, 0.16],
       [0.3 , 0.  , 0.83],
       [0.64, 0.5 , 0.02],
       [0.2 , 0.02, 0.86]])

In [ ]:
dfx=pd.DataFrame(
    np.random.rand(10,3).round(2),columns=["a","b","c"]
)

In [ ]:
dfx.to_excel("abc.xlsx")

In [ ]:
pd.read_excel("abc.xlsx")

   Unnamed: 0     a     b     c
0           0  0.97  0.25  0.12
1           1  0.54  0.60  0.84
2           2  0.85  0.51  0.05
3           3  0.72  0.90  0.53
4           4  0.56  0.45  0.89
5           5  0.20  0.60  0.61
6           6  0.59  0.05  0.38
7           7  0.38  0.70  0.99
8           8  0.32  0.43  0.77
9           9  0.68  0.93  0.79

In [ ]:
pd.read_excel("abc.xlsx",index_col="Unnamed: 0")

      a     b     c
0  0.97  0.25  0.12
1  0.54  0.60  0.84
2  0.85  0.51  0.05
3  0.72  0.90  0.53
4  0.56  0.45  0.89
5  0.20  0.60  0.61
6  0.59  0.05  0.38
7  0.38  0.70  0.99
8  0.32  0.43  0.77
9  0.68  0.93  0.79

In [ ]:
df['d']=np.random.randint(0,10,5)

In [ ]:
df.describe(include="all")

                A    b        dd         d
count    5.000000    5  5.000000  5.000000
unique        NaN    5       NaN       NaN
top           NaN    a       NaN       NaN
freq          NaN    1       NaN       NaN
mean    30.000000  NaN  6.200000  6.000000
std     15.811388  NaN  3.563706  3.535534
min     10.000000  NaN  1.000000  0.000000
25%     20.000000  NaN  4.000000  6.000000
50%     30.000000  NaN  8.000000  7.000000
75%     40.000000  NaN  9.000000  8.000000
max     50.000000  NaN  9.000000  9.000000

In [ ]:
df['m']=np.random.choice(['a','b','c','d','e'],5)

In [ ]:
df.drop('m',axis=1,inplace=True)

how to use conditions to create a new column

In [ ]:
df['d'].apply(lambda x:'big' if x>5 else 'small')

0      big
1      big
2      big
3    small
4      big
Name: d, dtype: object

In [ ]:
df['dd']= df['d'].apply(lambda x:'big' if x>5 else 'small')

In [ ]:
df

    A  b     dd  d
0  10  a    big  9
1  20  b    big  8
2  30  c    big  6
3  40  d  small  0
4  50  e    big  7

In [ ]:
np.arange(1,100,10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
dfx.set_index(np.arange(1,100,10))

       a     b     c
1   0.97  0.25  0.12
11  0.54  0.60  0.84
21  0.85  0.51  0.05
31  0.72  0.90  0.53
41  0.56  0.45  0.89
51  0.20  0.60  0.61
61  0.59  0.05  0.38
71  0.38  0.70  0.99
81  0.32  0.43  0.77
91  0.68  0.93  0.79

In [ ]:
dfx.loc[4,'b']

np.float64(0.45)

In [ ]:
dfx.iloc[2,2]

np.float64(0.05)

In [2]:
import pandas as pd
import numpy as np

dfx=pd.DataFrame(
    np.random.rand(10,3).round(2),columns=["a","b","c"]
)
dfx.iloc[2,-1]

np.float64(0.79)

range of index

In [3]:
st="this is python"

In [4]:
st[2:12:3]

'iiph'

In [5]:
ar=np.random.randint(11,99,(2,3,4))

In [6]:
ar

array([[[24, 41, 66, 46],
        [64, 75, 63, 93],
        [21, 40, 16, 32]],

       [[97, 44, 85, 40],
        [40, 14, 14, 66],
        [96, 74, 15, 21]]])

In [7]:
ar=np.random.randint(11,99,(4,5,6))
ar

array([[[55, 22, 11, 17, 39, 89],
        [45, 64, 17, 15, 84, 61],
        [24, 43, 11, 21, 96, 12],
        [57, 86, 92, 65, 69, 64],
        [74, 61, 13, 14, 30, 85]],

       [[39, 51, 92, 84, 11, 22],
        [94, 42, 18, 60, 55, 34],
        [79, 68, 88, 24, 93, 68],
        [82, 17, 94, 75, 82, 92],
        [46, 22, 50, 51, 57, 90]],

       [[68, 68, 38, 13, 53, 49],
        [95, 26, 12, 76, 15, 25],
        [15, 86, 66, 79, 54, 55],
        [81, 15, 86, 33, 55, 52],
        [87, 57, 56, 96, 68, 33]],

       [[23, 78, 80, 32, 24, 37],
        [12, 75, 92, 81, 24, 93],
        [95, 50, 25, 49, 64, 94],
        [31, 76, 41, 64, 75, 93],
        [56, 83, 91, 59, 30, 54]]])

In [8]:
ar[1,2,3]

np.int64(24)

for entire row display we use ":"

In [9]:
ar[2,3,:]

array([81, 15, 86, 33, 55, 52])

In [10]:
ar[2,:,:]

array([[68, 68, 38, 13, 53, 49],
       [95, 26, 12, 76, 15, 25],
       [15, 86, 66, 79, 54, 55],
       [81, 15, 86, 33, 55, 52],
       [87, 57, 56, 96, 68, 33]])

In [11]:
ar[2,:,2]

array([38, 12, 66, 86, 56])

In [12]:
ar[:,:,:]

array([[[55, 22, 11, 17, 39, 89],
        [45, 64, 17, 15, 84, 61],
        [24, 43, 11, 21, 96, 12],
        [57, 86, 92, 65, 69, 64],
        [74, 61, 13, 14, 30, 85]],

       [[39, 51, 92, 84, 11, 22],
        [94, 42, 18, 60, 55, 34],
        [79, 68, 88, 24, 93, 68],
        [82, 17, 94, 75, 82, 92],
        [46, 22, 50, 51, 57, 90]],

       [[68, 68, 38, 13, 53, 49],
        [95, 26, 12, 76, 15, 25],
        [15, 86, 66, 79, 54, 55],
        [81, 15, 86, 33, 55, 52],
        [87, 57, 56, 96, 68, 33]],

       [[23, 78, 80, 32, 24, 37],
        [12, 75, 92, 81, 24, 93],
        [95, 50, 25, 49, 64, 94],
        [31, 76, 41, 64, 75, 93],
        [56, 83, 91, 59, 30, 54]]])

In [13]:
ar[:,3,2]

array([92, 94, 86, 41])

In [14]:
ar[:,3,:]

array([[57, 86, 92, 65, 69, 64],
       [82, 17, 94, 75, 82, 92],
       [81, 15, 86, 33, 55, 52],
       [31, 76, 41, 64, 75, 93]])

In [15]:
ar[:,:,2]

array([[11, 17, 11, 92, 13],
       [92, 18, 88, 94, 50],
       [38, 12, 66, 86, 56],
       [80, 92, 25, 41, 91]])

In [16]:
ar[2,:,:]

array([[68, 68, 38, 13, 53, 49],
       [95, 26, 12, 76, 15, 25],
       [15, 86, 66, 79, 54, 55],
       [81, 15, 86, 33, 55, 52],
       [87, 57, 56, 96, 68, 33]])

In [17]:
ar[2,:,2].shape

(5,)

for 2 dimension

In [19]:
ar2=np.random.randint(11,12,9)

In [20]:
ar2

array([11, 11, 11, 11, 11, 11, 11, 11, 11])

In [21]:
newar = np.zeros((7,3,5,9))

In [22]:
newar.shape

(7, 3, 5, 9)

In [29]:
newar[2,2,4,6].shape

()

In [26]:
newar[:,2,4,8].shape

(7,)

In [27]:
newar[5,:,2,8].shape

(3,)

In [30]:
newar[2:5,1:3,2:4,2:6].shape

(3, 2, 2, 4)

Range of index in pandas

In [31]:
ndf = pd.DataFrame({
    'first':np.random.randint(11,99,10),
    'second':np.random.randint(11,99,10),
    'third':np.random.randint(11,99,10)
})

In [34]:
ndf

   first  second  third
0     31      50     88
1     63      57     12
2     32      56     48
3     75      63     58
4     36      11     81
5     91      98     78
6     19      33     54
7     74      75     16
8     84      83     41
9     35      58     56

In [36]:
ndf.set_index(np.arange(10,20),inplace=True)

In [39]:
ndf.iloc[5,1]

np.int64(98)

In [40]:
ndf.iloc[:,2] #all of the rows and restricted to 2nd column

10    88
11    12
12    48
13    58
14    81
15    78
16    54
17    16
18    41
19    56
Name: third, dtype: int64

In [41]:
ndf.loc[15,"second"]

np.int64(98)

In [42]:
ndf.iloc[6,:] #restricted to sixth row but all the column

first     19
second    33
third     54
Name: 16, dtype: int64

In [44]:
ndf.iloc[3:8,2:4]

    third
13     58
14     81
15     78
16     54
17     16