<a href="https://colab.research.google.com/github/kapuGayathri/Pandas/blob/main/thirdclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
if 5<3:
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)
print("end")

end

In [2]:
if 5<3:
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)
  print("end")

functions

In [3]:
def xyz():
  print("yes")
  c=3
  x=7
  m=c+x
  print(m)

In [4]:
xyz()

yes
10

In [5]:
def mnp(m):
  k=10
  c=m+k
  print(c)

In [7]:
mnp(9)

19

In [8]:
def mnp(m,n,p='mango'):
  print(p)

In [9]:
mnp(9,12)

mango

In [10]:
type(100)

int

In [11]:
def newf():
  print(100)
  print(200)
newf()

100
200

In [12]:
def newf():
  print(100)
  print(200)
  return 150
newf()

100
200

150

In [14]:
def newf():
  print(100)
  print(200)
  return 150
newf()

100
200

150

In [16]:
def onef(x):
 return x*7 +23

In [17]:
twof=lambda x: x*7+23

In [20]:
twof(5)

58

In [21]:
import numpy as np
import pandas as pd

In [25]:
pd.DataFrame({
    "A":[10,20,30,40,50],
    "b":['a','b','c','d','e']
})

    A  b
0  10  a
1  20  b
2  30  c
3  40  d
4  50  e

In [31]:
pd.DataFrame({
    "A":[10,20,30,40,50],
    "b":['a','b','c','d','e'],
    "c":np.random.randint(65)
})

    A  b   c
0  10  a  52
1  20  b  52
2  30  c  52
3  40  d  52
4  50  e  52

In [36]:
pd.DataFrame(
    np.random.randint(0,9,(10,4)),columns=["a","b","c","d"]
)

   a  b  c  d
0  5  8  2  4
1  4  3  4  0
2  2  0  8  1
3  2  1  3  0
4  1  0  6  7
5  4  3  7  6
6  7  8  4  1
7  5  5  5  5
8  0  7  6  0
9  8  2  6  8

In [37]:
np.random.rand(10,3)

array([[0.17990643, 0.23586317, 0.70072275],
       [0.24875609, 0.49165861, 0.43957495],
       [0.81348816, 0.0758525 , 0.59295069],
       [0.0552067 , 0.52798709, 0.76563763],
       [0.89332913, 0.75429337, 0.65314467],
       [0.92889835, 0.76540823, 0.03803804],
       [0.63612406, 0.12650306, 0.73403244],
       [0.15124685, 0.31784389, 0.26012324],
       [0.27242753, 0.89310492, 0.9270984 ],
       [0.7274041 , 0.62609354, 0.85764748]])

In [39]:
np.random.rand(10,3).round(2)

array([[0.42, 0.58, 0.73],
       [0.97, 0.95, 0.48],
       [0.27, 0.93, 0.57],
       [0.95, 0.67, 0.94],
       [0.25, 0.87, 0.36],
       [0.62, 0.89, 0.91],
       [0.02, 0.62, 0.16],
       [0.3 , 0.  , 0.83],
       [0.64, 0.5 , 0.02],
       [0.2 , 0.02, 0.86]])

In [46]:
dfx=pd.DataFrame(
    np.random.rand(10,3).round(2),columns=["a","b","c"]
)

In [49]:
dfx.to_excel("abc.xlsx")

In [50]:
pd.read_excel("abc.xlsx")

   Unnamed: 0     a     b     c
0           0  0.97  0.25  0.12
1           1  0.54  0.60  0.84
2           2  0.85  0.51  0.05
3           3  0.72  0.90  0.53
4           4  0.56  0.45  0.89
5           5  0.20  0.60  0.61
6           6  0.59  0.05  0.38
7           7  0.38  0.70  0.99
8           8  0.32  0.43  0.77
9           9  0.68  0.93  0.79

In [51]:
pd.read_excel("abc.xlsx",index_col="Unnamed: 0")

      a     b     c
0  0.97  0.25  0.12
1  0.54  0.60  0.84
2  0.85  0.51  0.05
3  0.72  0.90  0.53
4  0.56  0.45  0.89
5  0.20  0.60  0.61
6  0.59  0.05  0.38
7  0.38  0.70  0.99
8  0.32  0.43  0.77
9  0.68  0.93  0.79

In [55]:
df['d']=np.random.randint(0,10,5)

In [56]:
df.describe(include="all")

                A    b        dd         d
count    5.000000    5  5.000000  5.000000
unique        NaN    5       NaN       NaN
top           NaN    a       NaN       NaN
freq          NaN    1       NaN       NaN
mean    30.000000  NaN  6.200000  6.000000
std     15.811388  NaN  3.563706  3.535534
min     10.000000  NaN  1.000000  0.000000
25%     20.000000  NaN  4.000000  6.000000
50%     30.000000  NaN  8.000000  7.000000
75%     40.000000  NaN  9.000000  8.000000
max     50.000000  NaN  9.000000  9.000000

In [59]:
df['m']=np.random.choice(['a','b','c','d','e'],5)

In [61]:
df.drop('m',axis=1,inplace=True)

how to use conditions to create a new column

In [63]:
df['d'].apply(lambda x:'big' if x>5 else 'small')

0      big
1      big
2      big
3    small
4      big
Name: d, dtype: object

In [65]:
df['dd']= df['d'].apply(lambda x:'big' if x>5 else 'small')

In [66]:
df

    A  b     dd  d
0  10  a    big  9
1  20  b    big  8
2  30  c    big  6
3  40  d  small  0
4  50  e    big  7